import { sectorItem } from '@/lib/scenarios/types';
import type { RiskItem } from './types';

/**
 * A pénzügyi alapadatokból (beszámoló, melléklet, könyvvizsgálói jelentés,
 * beírt tények) szabállyal javasolt tételek sablonjai. Stabil kóddal (PA-xx),
 * hogy a tudástár és a riport ugyanúgy kezelje őket, mint a katalógust.
 * Alapból nem azonosítottak: csak elfogadott javaslatként kerülnek a mátrixba.
 */
const item = (r: Parameters<typeof sectorItem>[0]) => sectorItem({ identified: false, ...r });

export const FINANCIAL_RISKS: RiskItem[] = [
  item({
    code: 'PA-01',
    pillar: 'FINANCE',
    title: 'Nem tiszta könyvvizsgálói vélemény',
    description: 'A könyvvizsgáló minősített véleményt, ellenvéleményt adott, vagy visszautasította a véleménynyilvánítást.',
    likelihood: 5,
    impact: 4,
    exposureHuf: 0,
    remediationDays: 30,
    remediation: 'A minősítés okainak feltárása, korrekciós könyvelések, szükség esetén a beszámoló módosítása.',
    division: 'ACCOUNTING',
    serviceFeeHuf: 1_500_000,
    reasoning:
      'A könyvvizsgáló nem tudta megerősíteni, hogy a beszámoló minden lényeges szempontból megbízható képet ad. A beszámoló számaira épülő értékelés és vételár így bizonytalan alapon áll; befektető vagy hitelező a minősítés okát elsőként vizsgálja.',
  }),
  item({
    code: 'PA-02',
    pillar: 'FINANCE',
    title: 'Bizonytalan a vállalkozás folytatása',
    description: 'A könyvvizsgálói jelentés lényeges bizonytalanságot jelez a vállalkozás folytatására vonatkozóan.',
    likelihood: 5,
    impact: 5,
    exposureHuf: 0,
    remediationDays: 20,
    remediation: 'Likviditási és tőkehelyzeti terv, finanszírozási megoldás, tulajdonosi döntések előkészítése.',
    division: 'ADVISORY',
    serviceFeeHuf: 2_000_000,
    reasoning:
      'A könyvvizsgáló szerint olyan események vagy körülmények állnak fenn, amelyek kétségessé tehetik a társaság működésének folytatását. Ez minden más megállapítást felülír: a tulajdonosnak és a vezetésnek sürgősen rendeznie kell a finanszírozást.',
  }),
  item({
    code: 'PA-03',
    pillar: 'LEGAL',
    title: 'Tőkevesztés: saját tőke a jegyzett tőke alatt',
    description: 'A saját tőke negatív, vagy nem éri el a jegyzett tőkét.',
    likelihood: 4,
    impact: 5,
    exposureHuf: 0,
    remediationDays: 30,
    remediation: 'Tőkerendezés (tőkeemelés, tagi kölcsön tőkésítése, pótbefizetés) vagy átalakulás jogászi előkészítéssel.',
    division: 'LEGAL',
    serviceFeeHuf: 1_200_000,
    reasoning:
      'A saját tőke a jegyzett tőke alá csökkent. A Ptk. tőkevédelmi szabályai ilyenkor a tagok számára intézkedési kötelezettséget írhatnak elő; a pontos feltételt (társasági forma, egymást követő évek) jogász ellenőrzi. Tranzakció előtt a tőkehelyzetet rendezni kell.',
  }),
  item({
    code: 'PA-04',
    pillar: 'FINANCE',
    title: 'Jelentős árbevétel-csökkenés',
    description: 'Az árbevétel az előző évhez képest jelentősen csökkent.',
    likelihood: 4,
    impact: 4,
    exposureHuf: 0,
    remediationDays: 15,
    remediation: 'Az okok elemzése vevőnként és termékenként; értékesítési akcióterv; a terv újrakalibrálása.',
    division: 'ADVISORY',
    serviceFeeHuf: 900_000,
    reasoning:
      'Az árbevétel érdemben visszaesett. Ha az ok nem egyszeri (pl. elvesztett kulcsvevő, piaci szűkülés), az a jövőbeli eredményt és az értékelést is lefelé viszi; a vevő ezt az üzleti terv hitelességénél vizsgálja.',
  }),
  item({
    code: 'PA-05',
    pillar: 'FINANCE',
    title: 'Romló jövedelmezőség (EBITDA)',
    description: 'Az EBITDA negatív, vagy az EBITDA-ráta érdemben romlott.',
    likelihood: 4,
    impact: 4,
    exposureHuf: 0,
    remediationDays: 20,
    remediation: 'Költségszerkezet- és árazás-felülvizsgálat, fedezetelemzés termék- és vevőszinten.',
    division: 'ADVISORY',
    serviceFeeHuf: 1_000_000,
    reasoning:
      'A működési eredmény romlik. Az értékelés jellemzően az EBITDA többszöröse, így a romló trend közvetlenül csökkenti a cég értékét és a hitelképességet.',
  }),
  item({
    code: 'PA-06',
    pillar: 'FINANCE',
    title: 'Magas eladósodottság',
    description: 'A nettó adósság az EBITDA többszörösét teszi ki.',
    likelihood: 3,
    impact: 4,
    exposureHuf: 0,
    remediationDays: 20,
    remediation: 'Adósságszerkezet és lejárati profil áttekintése, refinanszírozási terv.',
    division: 'ADVISORY',
    serviceFeeHuf: 900_000,
    reasoning:
      'A társaság adósságállománya a működési eredményhez képest magas. Ez szűkíti a mozgásteret, drágítja a további finanszírozást, és tranzakciónál a vételárból levonásra kerül.',
  }),
  item({
    code: 'PA-07',
    pillar: 'FINANCE',
    title: 'Gyenge likviditás',
    description: 'A forgóeszközök nem fedezik a rövid lejáratú kötelezettségeket.',
    likelihood: 4,
    impact: 4,
    exposureHuf: 0,
    remediationDays: 10,
    remediation: '13 hetes cash-flow terv, forgótőke-menedzsment (vevőbeszedés, készlet), rövid távú finanszírozás.',
    division: 'ACCOUNTING',
    serviceFeeHuf: 600_000,
    reasoning: 'A rövid lejáratú kötelezettségek meghaladják a forgóeszközöket. Egy késve fizető vevő vagy szezonális csúcs fizetési nehézséget okozhat.',
  }),
  item({
    code: 'PA-08',
    pillar: 'FINANCE',
    title: 'Adótartozás vagy nem köztartozásmentes adózó',
    description: 'A NAV-folyószámlán tartozás van, vagy a társaság nem szerepel a köztartozásmentes adatbázisban.',
    likelihood: 4,
    impact: 3,
    exposureHuf: 0,
    remediationDays: 10,
    remediation: 'Folyószámla-egyeztetés, tartozás rendezése vagy fizetési könnyítés, a köztartozásmentes státusz visszaszerzése.',
    division: 'TAX',
    serviceFeeHuf: 400_000,
    reasoning:
      'A NAV felé fennálló tartozás pótlékot és végrehajtást vonhat maga után, és kizárhat közbeszerzésből, támogatásból. A köztartozásmentes státusz hiánya üzleti partnereknél is bizalmi kérdés.',
  }),
  item({
    code: 'PA-09',
    pillar: 'FINANCE',
    title: 'Adóellenőrzési megállapítás, gyakori önellenőrzés',
    description: 'Az utolsó adóellenőrzés megállapítással zárult, vagy sok az önellenőrzés.',
    likelihood: 3,
    impact: 3,
    exposureHuf: 0,
    remediationDays: 15,
    remediation: 'A megállapítások okainak felszámolása, adózási folyamatok és belső kontrollok felülvizsgálata.',
    division: 'TAX',
    serviceFeeHuf: 800_000,
    reasoning: 'Az ismétlődő hibák a könyvelési és adózási folyamatok gyengeségére utalnak. A még nem ellenőrzött időszakokra hasonló kockázat valószínű.',
  }),
  item({
    code: 'PA-10',
    pillar: 'LEGAL',
    title: 'Jelentős függő kötelezettség (kezesség, garancia)',
    description: 'A melléklet vagy a tájékoztatás szerint a társaság jelentős kezességet, garanciát vállalt.',
    likelihood: 3,
    impact: 4,
    exposureHuf: 0,
    remediationDays: 10,
    remediation: 'A kötelezettségvállalások listázása, lehívási kockázat felmérése, tranzakciónál kártalanítási kikötés.',
    division: 'LEGAL',
    serviceFeeHuf: 600_000,
    reasoning:
      'A mérlegen kívüli kötelezettség a beszámolóban nem jelenik meg tartozásként, de lehívás esetén a társaságot terheli. Vevő ezt adósságként kezeli vagy szavatossági nyilatkozatot kér rá.',
  }),
  item({
    code: 'PA-11',
    pillar: 'LEGAL',
    title: 'Folyamatban lévő perek',
    description: 'A társaságnak folyamatban lévő peres eljárása van.',
    likelihood: 3,
    impact: 4,
    exposureHuf: 0,
    remediationDays: 10,
    remediation: 'Ügyvédi értékelés a várható kimenetelről, céltartalék-képzés vizsgálata, tranzakciós kikötések.',
    division: 'LEGAL',
    serviceFeeHuf: 700_000,
    reasoning: 'A perek kimenetele bizonytalan; a perérték és a költségek az eredményt és a likviditást terhelhetik.',
  }),
  item({
    code: 'PA-12',
    pillar: 'LEGAL',
    title: 'Támogatás fenntartási kötelezettséggel',
    description: 'Elnyert támogatás fenntartási idővel; tulajdonosváltáshoz hozzájárulás kellhet.',
    likelihood: 3,
    impact: 4,
    exposureHuf: 0,
    remediationDays: 15,
    remediation: 'A támogatási szerződés feltételeinek áttekintése, a támogató hozzájárulásának beszerzése, megfelelés dokumentálása.',
    division: 'LEGAL',
    serviceFeeHuf: 700_000,
    reasoning:
      'A fenntartási időszak alatt a feltételek megsértése (pl. létszám, tevékenység, tulajdonosi kör változása) a támogatás részleges vagy teljes visszafizetését vonhatja maga után.',
  }),
  item({
    code: 'PA-13',
    pillar: 'FINANCE',
    title: 'Hitelkovenáns-sértés vagy tulajdonosváltási záradék a hitelben',
    description: 'A kovenánsok nem teljesülnek, vagy a hitelszerződés tulajdonosváltáskor felmondható.',
    likelihood: 4,
    impact: 4,
    exposureHuf: 0,
    remediationDays: 15,
    remediation: 'Egyeztetés a bankkal (waiver), refinanszírozási lehetőségek, a záradék kezelése a tranzakciós menetrendben.',
    division: 'ADVISORY',
    serviceFeeHuf: 800_000,
    reasoning: 'A bank a hitelt lejárttá teheti. Tranzakciónál a hitel előtörlesztése vagy a bank hozzájárulása a zárás feltétele lehet.',
  }),
  item({
    code: 'PA-14',
    pillar: 'FINANCE',
    title: 'Közeli hitellejárat',
    description: 'Jelentős hitel jár le a következő hónapokban.',
    likelihood: 3,
    impact: 3,
    exposureHuf: 0,
    remediationDays: 10,
    remediation: 'Refinanszírozás időben, likviditási terv a lejáratra.',
    division: 'ADVISORY',
    serviceFeeHuf: 500_000,
    reasoning: 'A lejáratkor a hitelt vissza kell fizetni vagy meg kell újítani; ha ez csúszik, likviditási szorulás jön.',
  }),
  item({
    code: 'PA-15',
    pillar: 'FINANCE',
    title: 'Tagi / tulajdonosi kölcsönök rendezetlenek',
    description: 'Jelentős tagi kölcsön áll fenn a társaság és a tulajdonos között.',
    likelihood: 3,
    impact: 3,
    exposureHuf: 0,
    remediationDays: 10,
    remediation: 'A kölcsönök dokumentálása és rendezése (visszafizetés, tőkésítés) a tranzakció előtt.',
    division: 'TAX',
    serviceFeeHuf: 500_000,
    reasoning: 'A tagi kölcsön tranzakciónál vételár-korrekciót igényel, és kamatfeltételei transzferár-szempontból is vizsgálandók.',
  }),
  item({
    code: 'PA-16',
    pillar: 'LEGAL',
    title: 'Késedelmes beszámoló-közzététel',
    description: 'A beszámolót a határidő után helyezték letétbe.',
    likelihood: 3,
    impact: 2,
    exposureHuf: 0,
    remediationDays: 3,
    remediation: 'Határidő-naptár, felelős kijelölése, a könyvelővel kötött szerződés felülvizsgálata.',
    division: 'ACCOUNTING',
    serviceFeeHuf: 150_000,
    reasoning: 'A késedelmes közzététel bírságot és cégbírósági eljárást vonhat maga után, és rossz képet ad a partnereknek.',
  }),
  item({
    code: 'PA-17',
    pillar: 'FINANCE',
    title: 'Osztalékfizetés gyenge tőkehelyzet mellett',
    description: 'Osztalékot hagytak jóvá, miközben a saját tőke a jegyzett tőke alatt van.',
    likelihood: 3,
    impact: 4,
    exposureHuf: 0,
    remediationDays: 10,
    remediation: 'Az osztalékfizetés jogszerűségének jogászi vizsgálata, szükség esetén visszafizetés.',
    division: 'LEGAL',
    serviceFeeHuf: 500_000,
    reasoning: 'Gyenge tőkehelyzetnél az osztalékfizetés a Ptk. tőkevédelmi szabályaiba ütközhet; a pontos feltételt jogász ellenőrzi.',
  }),
  item({
    code: 'PA-18',
    pillar: 'FINANCE',
    title: 'Belső kontroll hiányosságai (vezetői levél)',
    description: 'A könyvvizsgáló vezetői levele kontrollhiányosságokat jelez.',
    likelihood: 3,
    impact: 3,
    exposureHuf: 0,
    remediationDays: 20,
    remediation: 'A jelzett hiányosságok intézkedési terve, felelősökkel és határidőkkel.',
    division: 'ACCOUNTING',
    serviceFeeHuf: 700_000,
    reasoning: 'A könyvvizsgáló által jelzett kontrollhiányosságok hibás könyveléshez, visszaéléshez, adózási kockázathoz vezethetnek.',
  }),
  item({
    code: 'PA-19',
    pillar: 'OPERATIONS',
    title: 'Nincs megfelelő felelősségbiztosítás',
    description: 'Nincs felelősségbiztosítás, vagy a limit a kitettséghez képest alacsony.',
    likelihood: 3,
    impact: 3,
    exposureHuf: 0,
    remediationDays: 10,
    remediation: 'Biztosítási igényfelmérés, megfelelő limitű felelősségbiztosítás megkötése.',
    division: 'ADVISORY',
    serviceFeeHuf: 300_000,
    reasoning: 'Egy nagyobb kárigény biztosítás nélkül közvetlenül a társaság eredményét és likviditását terheli.',
  }),
  item({
    code: 'PA-20',
    pillar: 'FINANCE',
    title: 'A beszámoló és az adattáblák nem egyeznek',
    description: 'A beszámoló árbevétele vagy vevőállománya eltér az ügyfél által adott tábláktól.',
    likelihood: 3,
    impact: 3,
    exposureHuf: 0,
    remediationDays: 5,
    remediation: 'Egyeztetés a könyveléssel: hiányos tábla, eltérő időszak vagy nem könyvelt tétel.',
    division: 'ACCOUNTING',
    serviceFeeHuf: 300_000,
    reasoning:
      'Ha a táblák nem egyeznek a beszámolóval, a rájuk épülő mutatók (koncentráció, korosítás) torzak lehetnek; az ok lehet ártatlan, de tisztázni kell.',
  }),
];

const BY_CODE = new Map(FINANCIAL_RISKS.map((r) => [r.code, r]));

export function financialRiskTemplate(code: string): RiskItem | undefined {
  return BY_CODE.get(code);
}
