import type { Role } from '@/lib/timesheet/timesheet';
import type { Division } from '@/lib/risk/types';
import type { PlanTemplate, StepTemplate } from './types';

/**
 * Javítási terv-sablonok: alapkatalógus és átvilágítás-típusonkénti tételek.
 * KEZDŐ JAVASLATOK: az óraszámokat a felelős üzletág hagyja jóvá; a tényleges
 * órák (óraszám-követés) alapján idővel pontosíthatók.
 */

export const P: Role = 'PARTNER';
export const S: Role = 'SENIOR';
export const J: Role = 'JUNIOR';

export const st = (label: string, detail: string, role: Role, hours: number, perUnit?: number, division?: Division): StepTemplate => ({
  label,
  detail,
  role,
  hours,
  ...(perUnit ? { perUnit } : {}),
  ...(division ? { division } : {}),
});

export const CORE_TEMPLATES: Record<string, PlanTemplate> = {
  'FIN-01': {
    goal: 'Elkészül a hiányzó transzferár-nyilvántartás a nyitott évekre, és eldől, kell-e önellenőrzés.',
    steps: [
      st('Kapcsolt ügyletek feltérképezése', 'A főkönyvből és a szerződésekből a kapcsolt felek és ügyletek listája, értékhatár szerint szűrve.', S, 6),
      st('Nyilvántartás ügyletenként', 'Funkció- és kockázatelemzés, módszerválasztás, összehasonlító adatok; a nyilvántartás megírása.', J, 2, 10),
      st('Szakmai felülvizsgálat ügyletenként', 'A módszer és a szokásos piaci ár ellenőrzése, eltérésnél korrekciós javaslat.', S, 0, 3),
      st('Önellenőrzési döntés', 'Ha az ár nem piaci: adóalap-korrekció és önellenőrzés számszerűsítése, döntési javaslat.', S, 6),
      st('Partneri jóváhagyás, egyeztetés', 'Eredmények átadása, egyeztetés a vezetéssel, aláírásra kész anyag.', P, 3),
    ],
    driver: { label: 'Nyilvántartás-köteles ügylet', unit: 'db', default: 4, fromValuation: true },
    spread: [0.85, 1.35],
    uncertainty: 'Az ügyletek összetettsége és az, hogy van-e használható összehasonlító adat; önellenőrzés esetén a korrekció mértéke.',
    client: { days: 3, who: 'pénzügyi vezető / könyvelő: szerződések, főkönyvi kivonatok, számlák' },
    external: ['Adatbázis-hozzáférés összehasonlító elemzéshez (ha nincs meglévő)'],
    assumptions: ['A szerződések és a számlák rendelkezésre állnak', 'Két nyitott évre készül nyilvántartás'],
  },
  'FIN-02': {
    goal: 'Normalizált EBITDA-híd: a riportált eredményből a fenntartható EBITDA, tételesen indokolt korrekciókkal.',
    steps: [
      st('Főkönyvi elemzés', 'Egyszeri, nem működési és tulajdonosi tételek kigyűjtése 2–3 évre.', J, 10),
      st('Korrekciók minősítése', 'Tételenként indoklás és bizonyíték (számla, szerződés), vitatható tételek jelölése.', S, 8),
      st('EBITDA-híd és összefoglaló', 'Évenkénti híd, érzékenység a vitatott tételekre, vezetői összefoglaló.', S, 4),
      st('Partneri felülvizsgálat', 'A korrekciók védhetőségének ellenőrzése vevői szemmel.', P, 2),
    ],
    spread: [0.8, 1.4],
    uncertainty: 'A korrekciós tételek száma és dokumentáltsága.',
    client: { days: 2, who: 'tulajdonos és pénzügyi vezető: tulajdonosi költségek magyarázata' },
    external: [],
    assumptions: ['Lezárt főkönyv 2–3 évre', 'Analitika elérhető'],
  },
  'FIN-03': {
    goal: 'Követeléskezelési szabályzat és értékvesztés-elszámolás, ami a lejárt állományt kezeli és a beszámolóban helyesen jelenik meg.',
    steps: [
      st('Vevőállomány korosítása', 'Korosított vevőlista, koncentráció vevőnként, behajthatósági besorolás.', J, 8),
      st('Értékvesztés-számítás', 'Értékvesztési javaslat tételenként a számviteli politika szerint, könyvelési tételek.', S, 6),
      st('Követeléskezelési szabályzat', 'Hitelkeret, fizetési felszólítás, behajtás és faktoring rendje, felelősökkel.', S, 8),
      st('Bevezetés és oktatás', 'A szabályzat bemutatása az értékesítésnek és a pénzügynek.', S, 3),
      st('Partneri felülvizsgálat', 'Szakmai jóváhagyás.', P, 1),
    ],
    spread: [0.85, 1.3],
    uncertainty: 'A vevőállomány mérete és az, hogy kell-e behajtási lépés egyes vevőknél.',
    client: { days: 2, who: 'pénzügy: vevőanalitika, vevői levelezés' },
    external: ['Behajtó cég vagy ügyvéd díja, ha jogi úton kell behajtani'],
    assumptions: ['Vevőanalitika exportálható a könyvelő programból'],
  },
  'FIN-04': {
    goal: 'A főkönyv és az ÁFA-bevallások egyeztetve; az eltérések oka feltárva, szükség esetén önellenőrzés beadva.',
    steps: [
      st('Egyeztetés időszakonként', 'Főkönyv – analitika – bevallás egyeztetése, eltérések listája.', J, 0, 3),
      st('Eltérések okának feltárása', 'Bizonylatszintű vizsgálat, téves könyvelések és bevallási hibák elkülönítése.', S, 4, 1),
      st('Önellenőrzés előkészítése', 'Javított bevallások és pótlékszámítás, ha az eltérés adóhiányt okozott.', S, 4),
      st('Folyamatjavaslat', 'Havi egyeztetési kontroll a könyvelésben, felelőssel.', S, 2),
      st('Partneri jóváhagyás', 'Az önellenőrzési döntés jóváhagyása.', P, 1),
    ],
    driver: { label: 'Egyeztetendő bevallási időszak', unit: 'hónap', default: 6 },
    spread: [0.8, 1.5],
    uncertainty: 'Az eltérések száma és hogy rendszerszintű vagy egyedi hibáról van-e szó.',
    client: { days: 2, who: 'könyvelő: analitikák, bevallások, bizonylatok' },
    external: ['Önellenőrzési pótlék és esetleges adókülönbözet (az ügyfél fizeti)'],
    assumptions: ['A NAV-on beadott bevallások elérhetők'],
  },
  'LEG-01': {
    goal: 'A tulajdonosváltási (change of control) záradék kezelése: partneri hozzájárulás (waiver) vagy módosított szerződés a tranzakció előtt.',
    steps: [
      st('Szerződések átvizsgálása', 'A záradékok pontos tartalma, felmondási és értesítési feltételek szerződésenként.', S, 2, 2),
      st('Tárgyalási stratégia', 'Mit kérünk (waiver, módosítás), mit adhatunk cserébe, időzítés a tranzakcióhoz.', P, 3),
      st('Waiver / módosítás tervezete', 'Hozzájáruló nyilatkozat vagy szerződésmódosítás szerződésenként.', S, 0, 3),
      st('Tárgyalás támogatása', 'Részvétel a partnerrel folytatott egyeztetéseken, válaszok a partner jogászának.', P, 2, 2),
      st('Üzleti hatás számszerűsítése', 'Mit jelent az árbevételre, ha a partner nem járul hozzá; tartalék-forgatókönyv.', S, 4, 0, 'ADVISORY'),
    ],
    driver: { label: 'Érintett kulcsszerződés', unit: 'db', default: 2 },
    spread: [0.7, 2],
    uncertainty: 'A partner hozzáállása: egy levélváltás vagy több tárgyalási kör.',
    client: { days: 2, who: 'ügyvezető: kapcsolattartás a partnerrel' },
    external: [],
    assumptions: ['A partner tárgyalóképes a tranzakció előtt'],
  },
  'LEG-02': {
    goal: 'A cég által használt szellemi alkotások vagyoni jogai igazoltan a cégnél vannak.',
    steps: [
      st('Érintett alkotók listája', 'Fejlesztők, alvállalkozók, volt munkatársak és jogviszonyuk feltérképezése.', J, 4),
      st('Átruházási szerződésminta', 'Munkavállalói és alvállalkozói minta a felhasználási és átruházási jogokkal.', S, 5),
      st('Egyedi szerződések elkészítése', 'Személyre szabott okirat alkotónként, ellenérték rendezésével.', J, 0, 1),
      st('Aláíratás és nyilvántartás', 'Aláírási folyamat koordinálása, IP-nyilvántartás felállítása.', J, 3, 0.5),
      st('Partneri felülvizsgálat', 'Kritikus alkotók és vitás esetek kezelése.', P, 2),
    ],
    driver: { label: 'Érintett alkotó (munkavállaló, alvállalkozó)', unit: 'fő', default: 8 },
    spread: [0.8, 1.5],
    uncertainty: 'Az elérhetetlen vagy ellenérdekelt volt alkotók száma.',
    client: { days: 2, who: 'ügyvezető / HR: alkotók elérése, aláíratás' },
    external: ['Esetleges ellenérték az alkotóknak'],
    assumptions: ['Az alkotók többsége elérhető'],
  },
  'LEG-03': {
    goal: 'A létesítő okirat és az SZMSZ a hatályos jogszabályoknak és a tényleges működésnek megfelel, bejegyezve.',
    steps: [
      st('Okiratok átvizsgálása', 'Eltérések a Ptk.-tól és a tényleges működéstől.', S, 3),
      st('Módosított okirat és határozat', 'Egységes szerkezetű okirat, taggyűlési határozat.', J, 3),
      st('Változásbejegyzés', 'Elektronikus cégeljárás, ügyvédi ellenjegyzés.', S, 2),
      st('Partneri jóváhagyás', 'Ellenjegyzés.', P, 1),
    ],
    spread: [0.85, 1.3],
    uncertainty: 'Hány ponton tér el az okirat és van-e tagi vita.',
    client: { days: 0.5, who: 'tagok: döntés és aláírás' },
    external: ['Cégbírósági illeték és közzétételi költségtérítés (ha van)'],
    assumptions: ['A tagok egyetértenek a módosításban'],
  },
  'LEG-04': {
    goal: 'GDPR-alapmegfelelés: adatkezelési nyilvántartás, tájékoztatók, adatfeldolgozói szerződések, incidenskezelési rend.',
    steps: [
      st('Gyorsaudit', 'Adatkezelések feltérképezése interjúkkal, hiánylista.', S, 6),
      st('Adatkezelési nyilvántartás', 'Folyamatonként cél, jogalap, megőrzési idő, címzettek.', J, 2, 2),
      st('Tájékoztatók és adatfeldolgozói szerződések', 'Munkavállalói és ügyfél-tájékoztató, adatfeldolgozói szerződések (DPA) a beszállítókkal.', S, 4, 1),
      st('Incidenskezelési szabályzat', 'Bejelentési rend, napló, felelős.', J, 3),
      st('Partneri felülvizsgálat', 'Kockázatos adatkezelések (pl. egészségügyi adat) kiemelt ellenőrzése.', P, 2),
    ],
    driver: { label: 'Adatkezelési folyamat', unit: 'db', default: 6 },
    spread: [0.8, 1.4],
    uncertainty: 'Az adatkezelések száma és érzékenysége (különleges adatok, megfigyelés).',
    client: { days: 2, who: 'folyamatgazdák: interjúk, beszállítói lista' },
    external: [],
    assumptions: ['Nincs folyamatban hatósági eljárás'],
  },
  'OPS-01': {
    goal: 'Minősített második beszállító és ellátásbiztonsági garanciákkal kötött keretszerződés.',
    steps: [
      st('Beszerzési kitettség elemzése', 'Volumen, alternatívák, váltási költség és idő.', S, 6),
      st('Alternatív beszállítók felkutatása', 'Hosszúlista, ajánlatkérés, rövidlista.', J, 12),
      st('Minősítés és döntés-előkészítés', 'Ajánlatok összevetése, kockázati értékelés, javaslat.', S, 8),
      st('Keretszerződés feltételei', 'Ellátási, árfolyam- és árgaranciák a szerződésben.', S, 6, 0, 'LEGAL'),
      st('Partneri felülvizsgálat', 'Döntési javaslat a vezetésnek.', P, 2),
    ],
    spread: [0.8, 1.6],
    uncertainty: 'A piac szűkössége: hány alkalmas beszállító van, kell-e próbagyártás.',
    client: { days: 4, who: 'beszerzés és termelés: specifikációk, mintavétel, próbarendelés' },
    external: ['Minta- és próbagyártás költsége'],
    assumptions: ['Van legalább két potenciális alternatív beszállító a piacon'],
  },
  'OPS-02': {
    goal: 'ERP-migrációs ütemterv és a kritikus folyamatok dokumentációja, amelyre a csere biztonságosan tervezhető.',
    steps: [
      st('Folyamatfelmérés', 'Kritikus üzleti folyamatok és integrációk dokumentálása interjúkkal.', S, 12),
      st('Követelménylista', 'Funkcionális és műszaki követelmények, adatmigrációs kör.', J, 10),
      st('Piaci opciók és költség', 'Szóba jöhető rendszerek, nagyságrendi költség és idő.', S, 8),
      st('Migrációs ütemterv', 'Szakaszok, kockázatok, döntési pontok, belső erőforrásigény.', S, 6),
      st('Partneri felülvizsgálat', 'Vezetői döntés-előkészítő.', P, 3),
    ],
    spread: [0.8, 1.5],
    uncertainty: 'A folyamatok és integrációk száma; a rendszerválasztás nem része (külön projekt).',
    client: { days: 4, who: 'folyamatgazdák és IT: interjúk, rendszerleírások' },
    external: ['A rendszerbevezetés díja (szállítói ajánlat alapján, nem része a díjnak)'],
    assumptions: ['A terv a döntésig tart; a bevezetés külön ajánlat'],
  },
  'OPS-03': {
    goal: 'Működő üzletmenet-folytonossági terv (BCP) és egy elvégzett mentés-visszaállítási teszt.',
    steps: [
      st('Üzleti hatáselemzés', 'Kritikus folyamatok, elfogadható kiesési idő és adatvesztés.', S, 6),
      st('BCP-dokumentum', 'Forgatókönyvek, felelősök, értesítési lánc, helyreállítási lépések.', J, 8),
      st('Visszaállítási teszt', 'A mentésből való visszaállítás próbája az IT-val, jegyzőkönyv.', S, 4),
      st('Partneri felülvizsgálat', 'Jóváhagyás, éves tesztrend.', P, 1),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'A mentési rendszer állapota: ha a teszt hibát talál, javítás szükséges.',
    client: { days: 2, who: 'IT és folyamatgazdák' },
    external: ['IT-szolgáltató díja a teszt idejére'],
    assumptions: ['Van rendszeres mentés'],
  },
  'OPS-04': {
    goal: 'Teljes engedély-nyilvántartás és megújítási naptár; a lejárt engedélyek megújítása elindítva.',
    steps: [
      st('Engedélyek összegyűjtése', 'Tevékenységenként szükséges és meglévő engedélyek összevetése.', J, 3, 0.5),
      st('Hiánypótlás jogi értékelése', 'Lejárt vagy hiányzó engedélyek kockázata, megújítási lépések.', S, 2, 0.5),
      st('Nyilvántartás és naptár', 'Felelős, határidő, emlékeztető.', J, 2),
    ],
    driver: { label: 'Engedély', unit: 'db', default: 6 },
    spread: [0.85, 1.4],
    uncertainty: 'A hiányzó engedélyek száma és a hatósági eljárások bonyolultsága.',
    client: { days: 1, who: 'ügyvezető: engedélyek másolatai' },
    external: ['Hatósági eljárási díjak, illetékek'],
    assumptions: ['A megújítási eljárások lefolytatása nem része (külön megbízás)'],
  },
  'OPS-05': {
    goal: 'Csökkenő vevőkoncentráció: hosszú távú keretszerződés a kulcsvevővel és értékesítési terv új vevőkre.',
    steps: [
      st('Vevőportfólió-elemzés', 'Fedezet és kockázat vevőnként, a kulcsvevő alku pozíciója.', S, 6),
      st('Keretszerződés feltételei', 'Időtartam, felmondási idő, mennyiségi vállalás a kulcsvevővel.', S, 6, 0, 'LEGAL'),
      st('Diverzifikációs akcióterv', 'Célszegmensek, célvevők, értékesítési lépések és mutatók.', S, 10),
      st('Partneri felülvizsgálat', 'Vezetői döntés-előkészítő.', P, 2),
    ],
    spread: [0.8, 1.5],
    uncertainty: 'A kulcsvevő hajlandósága hosszabb elköteleződésre.',
    client: { days: 3, who: 'értékesítés: vevőadatok, tárgyalás' },
    external: [],
    assumptions: ['Az akcióterv végrehajtása (értékesítés) az ügyfél feladata'],
  },
  'HR-01': {
    goal: 'Kulcsember-kockázat kezelve: utódlási terv, megtartási ösztönző és versenytilalmi megállapodás.',
    steps: [
      st('Kulcspozíciók felmérése', 'Ki pótolhatatlan, milyen tudás és ügyfélkapcsolat kötődik hozzá.', S, 2, 2),
      st('Utódlási terv', 'Helyettes kijelölése, tudásátadási ütemterv pozíciónként.', S, 0, 3),
      st('Megtartási ösztönző', 'Retenciós bónusz vagy részesedés (MRP) konstrukciója.', S, 6),
      st('Versenytilalmi megállapodások', 'Megállapodás és ellenérték pozíciónként.', S, 0, 2, 'LEGAL'),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    driver: { label: 'Kulcsember', unit: 'fő', default: 2 },
    spread: [0.8, 1.5],
    uncertainty: 'A kulcsemberek hajlandósága és az ösztönző formája (bónusz vagy részesedés).',
    client: { days: 2, who: 'tulajdonos: egyeztetések a kulcsemberekkel' },
    external: ['A retenciós bónusz és a versenytilalmi ellenérték összege'],
    assumptions: [],
  },
  'HR-02': {
    goal: 'A színlelt vállalkozói jogviszonyok átminősítve vagy jogszerűen átalakítva, a visszamenőleges kockázat számszerűsítve.',
    steps: [
      st('Jogviszonyok minősítése', 'Szerződések és tényleges munkavégzés vizsgálata jogviszonyonként.', S, 2, 1.5, 'LEGAL'),
      st('Kockázat számszerűsítése', 'Visszamenőleges járulék- és adókockázat, bírság.', S, 2, 0.5, 'TAX'),
      st('Átalakítási javaslat', 'Munkaviszony, valódi vállalkozás vagy más konstrukció; költségösszevetés.', S, 6),
      st('Új szerződések', 'Munkaszerződések vagy átdolgozott vállalkozói szerződések.', J, 0, 1.5, 'LEGAL'),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    driver: { label: 'Érintett jogviszony', unit: 'db', default: 5 },
    spread: [0.85, 1.4],
    uncertainty: 'Az érintettek száma és hogy indokolt-e önellenőrzés a múltra.',
    client: { days: 2, who: 'HR és vezetők: munkaköri leírások, munkavégzés módja' },
    external: ['Esetleges önellenőrzési pótlék és járulékkülönbözet'],
    assumptions: [],
  },
  'HR-03': {
    goal: 'Jogszabálynak megfelelő munkaidő-nyilvántartás és belső szabályzat.',
    steps: [
      st('Jelenlegi gyakorlat felmérése', 'Munkarendek, túlóra, távmunka.', J, 3),
      st('Szabályzat és nyilvántartási minta', 'Munkaidő-beosztás, nyilvántartás, túlóra-elrendelés.', S, 5),
      st('Bevezetés', 'Rövid tájékoztató a vezetőknek.', S, 2),
    ],
    spread: [0.85, 1.3],
    uncertainty: 'Kell-e elektronikus rendszer választása (külön díj).',
    client: { days: 1, who: 'HR' },
    external: ['Munkaidő-nyilvántartó szoftver díja, ha kell'],
    assumptions: [],
  },
  'HR-04': {
    goal: 'Versenyképes bér- és ösztönzőrendszer, amely a fluktuációt csökkenti.',
    steps: [
      st('Bérbenchmark', 'Pozíciónkénti piaci összevetés.', S, 8),
      st('Fluktuációs okok', 'Kilépési adatok és interjúk elemzése.', J, 6),
      st('Ösztönzőrendszer', 'Teljesítménybónusz, béren kívüli juttatás, MRP vagy BVKK konstrukció.', S, 10),
      st('Költséghatás és bevezetési terv', 'Bértömeg-hatás, ütemezés, kommunikáció.', S, 4),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'A pozíciók száma és a választott ösztönző bonyolultsága.',
    client: { days: 2, who: 'HR és pénzügy: béradatok' },
    external: ['Bérfelmérés vásárlása, ha kell'],
    assumptions: [],
  },
  'HC-01': {
    goal: 'Éves üzleti terv és havi vezetői riport 8–10 mutatóval, amelyből a vezetés dönt.',
    steps: [
      st('Mutatók kiválasztása', 'A vezetés céljaihoz illő pénzügyi és működési mutatók.', S, 4),
      st('Üzleti terv', 'Árbevétel-, költség- és cash-flow terv havi bontásban.', S, 10),
      st('Riportsablon és adatforrások', 'Excel- vagy BI-sablon, adatforrás mutatónként, felelős.', J, 8),
      st('Első havi riport közös elkészítése', 'Bevezetés és oktatás.', S, 4),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'Az adatok hozzáférhetősége a könyvelésből és a működési rendszerekből.',
    client: { days: 3, who: 'ügyvezető és pénzügy' },
    external: [],
    assumptions: [],
  },
  'HC-02': {
    goal: '13 hetes gördülő cash-flow előrejelzés bevezetve, heti frissítéssel.',
    steps: [
      st('Pénzforgalmi adatok', 'Bank, vevő- és szállítóanalitika, fix kifizetések.', J, 4),
      st('Modell felépítése', 'Heti bontású modell, forgatókönyvek.', S, 8),
      st('Bevezetés és oktatás', 'Heti frissítés rendje, felelős.', S, 3),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 1),
    ],
    spread: [0.85, 1.3],
    uncertainty: 'A bankszámlák és üzletágak száma.',
    client: { days: 1, who: 'pénzügy' },
    external: [],
    assumptions: [],
  },
  'VDD-01': {
    goal: 'A tulajdonosi és kapcsolt tartozások rendezve vagy szerződésben rögzítve, a tranzakciós adóhatás ismert.',
    steps: [
      st('Tételek összegyűjtése', 'Tulajdonosi kölcsönök, kapcsolt követelések és tartozások egyeztetése.', J, 4, 1),
      st('Rendezési opciók és adóhatás', 'Visszafizetés, beszámítás, tőkésítés: adó- és illetékhatás.', S, 4, 1),
      st('Dokumentáció', 'Kölcsönszerződések, megállapodások, határozatok.', S, 0, 1.5, 'LEGAL'),
      st('Partneri jóváhagyás', 'A választott megoldás jóváhagyása.', P, 2),
    ],
    driver: { label: 'Rendezendő tétel', unit: 'db', default: 4 },
    spread: [0.85, 1.4],
    uncertainty: 'A tételek száma és a hiányzó szerződések pótlásának nehézsége.',
    client: { days: 1, who: 'tulajdonos és könyvelő' },
    external: [],
    assumptions: [],
  },
  'VDD-02': {
    goal: 'Vevői átvilágításra kész adatszoba: struktúra, hiánylista, pótolt dokumentumok.',
    steps: [
      st('Adatszoba-struktúra', 'Mappaszerkezet a szokásos vevői kérdéslista szerint.', S, 3),
      st('Hiánylista', 'A meglévő iratok összevetése a struktúrával.', J, 6),
      st('Dokumentumpótlás koordinálása', 'A hiányzó iratok bekérése és ellenőrzése.', J, 10),
      st('Minőségellenőrzés', 'Érzékeny adatok, ellentmondások, aktualitás.', S, 6),
      st('Partneri felülvizsgálat', 'Megnyitás előtti jóváhagyás.', P, 2),
    ],
    spread: [0.8, 1.5],
    uncertainty: 'A hiányzó iratok mennyisége.',
    client: { days: 4, who: 'pénzügy, HR, jog: iratok összegyűjtése' },
    external: ['Virtuális adatszoba szolgáltatás díja'],
    assumptions: [],
  },
  'BUY-01': {
    goal: 'Az adásvételi szerződésben a feltárt kockázatokra specifikus kártalanítás és vételár-visszatartás (escrow).',
    steps: [
      st('Feltárt tételek beárazása', 'A kockázatok forintosítása kártalanítási célra.', S, 6, 0, 'ADVISORY'),
      st('Szerződéses mechanizmus', 'Specifikus kártalanítás, escrow, határidők és limitek megfogalmazása.', S, 10),
      st('Tárgyalás támogatása', 'Részvétel a tárgyalásokon, eladói ellenjavaslatok kezelése.', P, 8),
      st('Escrow-megállapodás', 'Letéti megállapodás és feltételek.', J, 4),
    ],
    spread: [0.8, 1.8],
    uncertainty: 'Az eladó tárgyalási pozíciója és a tárgyalási körök száma.',
    client: { days: 1, who: 'vevő döntéshozója' },
    external: ['Letétkezelő (bank, közjegyző, ügyvéd) díja'],
    assumptions: [],
  },
  'BUY-02': {
    goal: 'A függő kötelezettségek teljes listája eladói nyilatkozattal, beárazva a vételárba.',
    steps: [
      st('Kötelezettségek kigyűjtése', 'Kezességek, garanciák, perek, hatósági eljárások, kötbérek.', J, 8),
      st('Lehívási kockázat értékelése', 'Valószínűség és összeg tételenként.', S, 6),
      st('Eladói nyilatkozat és szavatosság', 'Szerződéses szöveg, szavatossági rendelkezések.', S, 6),
      st('Partneri felülvizsgálat', 'Vételár-korrekciós javaslat.', P, 2),
    ],
    spread: [0.85, 1.5],
    uncertainty: 'Az eladó adatszolgáltatásának teljessége.',
    client: { days: 1, who: 'vevő' },
    external: [],
    assumptions: [],
  },
  'FIK-01': {
    goal: 'Kovenáns-előrejelzés és a bankkal még a megsértés előtt egyeztetett megoldás.',
    steps: [
      st('Kovenánsok és számítás', 'A hitelszerződések kovenánsai, számítási mód, aktuális értékek.', S, 4),
      st('Előrejelzés', '12 hónapos előrejelzés kovenánsonként, érzékenység.', S, 6),
      st('Banki egyeztetés előkészítése', 'Waiver- vagy módosítási kérelem, intézkedési terv.', S, 4),
      st('Partneri részvétel', 'Banki tárgyalás támogatása.', P, 3),
    ],
    spread: [0.85, 1.5],
    uncertainty: 'A bank hozzáállása és a hitelszerződések száma.',
    client: { days: 1, who: 'pénzügyi vezető' },
    external: ['Banki módosítási díj'],
    assumptions: [],
  },
  'FIK-02': {
    goal: '12 hónapos, havi bontású cash-flow és finanszírozási terv, érzékenységvizsgálattal.',
    steps: [
      st('Adatgyűjtés', 'Terv, szerződések, beruházások, hitelek.', J, 4),
      st('Modell', 'Havi cash-flow, finanszírozási igény, forgatókönyvek.', S, 8),
      st('Érzékenység és összefoglaló', 'Kulcsfeltevések hatása, banknak szóló összefoglaló.', S, 3),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 1),
    ],
    spread: [0.85, 1.3],
    uncertainty: 'A tervadatok minősége.',
    client: { days: 1, who: 'pénzügy' },
    external: [],
    assumptions: [],
  },
  'SUC-01': {
    goal: 'Aláírt tulajdonosi (szindikátusi) megállapodás: döntéshozatal, kilépés, elővásárlás, értékelési mechanizmus.',
    steps: [
      st('Tulajdonosi interjúk', 'Célok, vitás pontok, családi szempontok tulajdonosonként.', S, 2, 1.5),
      st('Megállapodás-tervezet', 'Döntéshozatal, holtpont, kilépés, elővásárlás, értékelés.', S, 12),
      st('Egyeztetés és véglegesítés', 'Tárgyalási körök a tulajdonosokkal.', P, 4, 1),
      st('Okirat-módosítás', 'A megállapodással összhangban a létesítő okirat módosítása.', J, 3),
    ],
    driver: { label: 'Tulajdonos', unit: 'fő', default: 3 },
    spread: [0.8, 1.8],
    uncertainty: 'A tulajdonosok közötti egyetértés mértéke.',
    client: { days: 2, who: 'tulajdonosok' },
    external: ['Közjegyzői díj, ha közokirat kell'],
    assumptions: [],
  },
  'SUC-02': {
    goal: 'A cég és a család vagyona leválasztva, piaci feltételű szerződésekkel, az átadás adózási terve elkészül.',
    steps: [
      st('Összefonódások feltérképezése', 'Közös eszközök, ingatlanok, költségek, kölcsönök.', J, 6),
      st('Leválasztási javaslat', 'Piaci feltételű bérleti és használati szerződések, eszközátadás.', S, 6),
      st('Adózási terv', 'Az átadás (ajándékozás, öröklés, adásvétel) adó- és illetékhatása.', S, 8),
      st('Szerződések', 'A leválasztáshoz szükséges okiratok.', S, 6, 0, 'LEGAL'),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    spread: [0.8, 1.6],
    uncertainty: 'Az összefonódó vagyonelemek száma, ingatlan érintettsége.',
    client: { days: 2, who: 'tulajdonos és családja' },
    external: ['Ingatlan-értékbecslés, földhivatali és közjegyzői díjak'],
    assumptions: [],
  },
  'CMP-01': {
    goal: 'A kötelező belső szabályzatok pótolva, felelősök kijelölve, a munkatársak oktatva.',
    steps: [
      st('Kötelező szabályzatok felmérése', 'Tevékenység és létszám szerint kötelező szabályzatok listája.', S, 3),
      st('Szabályzatok elkészítése', 'Szabályzatonként testre szabott dokumentum.', J, 0, 4),
      st('Felülvizsgálat', 'Szakmai ellenőrzés szabályzatonként.', S, 0, 1),
      st('Oktatás', 'Munkatársi oktatás és jelenléti ív.', S, 3),
    ],
    driver: { label: 'Pótlandó szabályzat', unit: 'db', default: 4 },
    spread: [0.85, 1.3],
    uncertainty: 'A pótlandó szabályzatok száma.',
    client: { days: 1, who: 'vezetés: jóváhagyás, oktatás szervezése' },
    external: [],
    assumptions: [],
  },
  'CMP-02': {
    goal: 'A kiemelt adókockázatú tételek felülvizsgálva, szükség esetén önellenőrzéssel rendezve.',
    steps: [
      st('Kockázati tételek kiválasztása', 'Kockázatelemzés alapján a vizsgálandó tételek köre.', S, 4),
      st('Tételes felülvizsgálat', 'Bizonylatok, szerződések, bevallások vizsgálata.', J, 4, 4),
      st('Megállapítások értékelése', 'Adókülönbözet, pótlék, önellenőrzési javaslat.', S, 2, 1.5),
      st('Partneri jóváhagyás', 'Döntés és kommunikáció.', P, 2),
    ],
    driver: { label: 'Vizsgálandó adótétel / adónem', unit: 'db', default: 3 },
    spread: [0.85, 1.5],
    uncertainty: 'A feltárt eltérések száma.',
    client: { days: 2, who: 'könyvelő: bizonylatok' },
    external: ['Önellenőrzési pótlék és adókülönbözet'],
    assumptions: [],
  },
  'PMI-01': {
    goal: 'Megtartási program az első 30 napban: bónusz, szerep és kommunikáció a kulcsembereknek.',
    steps: [
      st('Kulcsemberek és kockázatuk', 'Kit és miért kell megtartani, mi a távozási kockázat.', S, 2, 1),
      st('Megtartási konstrukció', 'Bónusz, szerep, karrierút; költség.', S, 6),
      st('Kommunikációs terv', 'Egyéni beszélgetések és csapatkommunikáció forgatókönyve.', S, 4),
      st('Szerződéses rögzítés', 'Megtartási megállapodások.', J, 0, 1, 'LEGAL'),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    driver: { label: 'Kulcsember', unit: 'fő', default: 5 },
    spread: [0.85, 1.4],
    uncertainty: 'A kulcsemberek száma.',
    client: { days: 2, who: 'új tulajdonos és vezetés' },
    external: ['A megtartási bónuszok összege'],
    assumptions: [],
  },
  'PMI-02': {
    goal: '100 napos integrációs terv: rendszerek, jóváhagyási rend és beszerzés egységesítése.',
    steps: [
      st('Kiinduló állapot felmérése', 'Rendszerek, folyamatok, jóváhagyási jogkörök mindkét cégnél.', S, 12),
      st('Integrációs terv', 'Munkaszakaszok, felelősök, mérföldkövek 100 napra.', S, 12),
      st('Projektiroda első hónapja', 'Heti státusz, kockázatkezelés.', J, 16),
      st('Partneri irányítás', 'Irányítóbizottsági ülések.', P, 6),
    ],
    spread: [0.8, 1.6],
    uncertainty: 'A rendszerek és telephelyek száma; a projektiroda további hónapjai külön díjasak.',
    client: { days: 5, who: 'mindkét cég vezetői' },
    external: ['Rendszerintegrációs szállítói díjak'],
    assumptions: ['Az ajánlat az első hónap projektirodáját tartalmazza'],
  },
};
