import type { Division } from '@/lib/risk/types';
import type { PlanTemplate } from './types';
import { J, P, S, st } from './templates.core';

/**
 * Javítási terv-sablonok: pénzügyi alapadatokból jövő tételek (PA-*) és
 * ágazati tételek. KEZDŐ JAVASLATOK, a felelős üzletág hagyja jóvá.
 */

export const EXTRA_TEMPLATES: Record<string, PlanTemplate> = {
  'PA-01': {
    goal: 'A könyvvizsgálói minősítés okai feltárva és javítva; a következő beszámolóhoz tiszta vélemény várható.',
    steps: [
      st('A minősítés okainak elemzése', 'A könyvvizsgálói jelentés és vezetői levél pontjainak feldolgozása, egyeztetés a könyvvizsgálóval.', S, 6),
      st('Korrekciós könyvelések', 'Az érintett tételenként a helyes elszámolás és a korrekció.', J, 4, 4),
      st('Szakmai felülvizsgálat', 'A korrekciók és a számviteli politika ellenőrzése tételenként.', S, 0, 1.5),
      st('Beszámoló-módosítás döntése', 'Kell-e a korábbi beszámolót módosítani, vagy a tárgyévben javítható.', P, 3),
    ],
    driver: { label: 'A minősítés alapjául szolgáló tétel', unit: 'db', default: 3 },
    spread: [0.8, 1.6],
    uncertainty: 'A minősített tételek száma és hogy visszamenőleges módosítás kell-e.',
    client: { days: 3, who: 'könyvelő és pénzügyi vezető' },
    external: ['A könyvvizsgáló díja a módosított beszámoló ismételt vizsgálatáért'],
    assumptions: [],
  },
  'PA-02': {
    goal: 'Likviditási és tőkehelyzeti terv, finanszírozási megoldás, előkészített tulajdonosi döntések a vállalkozás folytatásához.',
    steps: [
      st('Helyzetfelmérés', 'Likviditás, lejáratok, tőkehelyzet, a könyvvizsgálói figyelemfelhívás okai.', S, 8),
      st('13 hetes és 12 hónapos cash-flow terv', 'Forgatókönyvekkel, finanszírozási igénnyel.', S, 12),
      st('Finanszírozási opciók', 'Banki, tulajdonosi, faktoring, átütemezés – feltételekkel.', S, 8),
      st('Tőkerendezés jogi előkészítése', 'Tőkeemelés vagy pótbefizetés határozatai.', S, 6, 0, 'LEGAL'),
      st('Partneri irányítás', 'Tulajdonosi és banki egyeztetések.', P, 8),
    ],
    spread: [0.8, 1.8],
    uncertainty: 'A helyzet súlyossága és a hitelezőkkel szükséges tárgyalások száma.',
    client: { days: 5, who: 'tulajdonos, ügyvezető, pénzügy' },
    external: ['Banki díjak, illetékek'],
    assumptions: [],
  },
  'PA-03': {
    goal: 'A saját tőke helyreállítva (tőkeemelés, tagi kölcsön tőkésítése, pótbefizetés) vagy előkészítve az átalakulás.',
    steps: [
      st('Tőkehelyzet és opciók', 'A Ptk. szerinti kötelezettség, határidő, megoldási lehetőségek.', S, 4),
      st('Adó- és számviteli hatás', 'Opciónként adó- és számviteli következmény.', S, 4, 0, 'TAX'),
      st('Határozatok és okiratok', 'Taggyűlési határozat, szerződések, okirat-módosítás.', S, 6),
      st('Cégeljárás', 'Változásbejegyzés.', J, 3),
      st('Partneri jóváhagyás', 'Ellenjegyzés.', P, 2),
    ],
    spread: [0.85, 1.5],
    uncertainty: 'Kell-e átalakulás vagy elég egy egyszerű tőkerendezés.',
    client: { days: 1, who: 'tulajdonosok' },
    external: ['Illeték és közzétételi költség'],
    assumptions: [],
  },
  'PA-04': {
    goal: 'Az árbevétel-csökkenés okai vevőnként és termékenként feltárva, értékesítési akcióterv és újrakalibrált terv.',
    steps: [
      st('Árbevétel-bontás', 'Vevő-, termék- és időszak-elemzés.', J, 10),
      st('Okok feltárása', 'Vezetői interjúk, piaci adatok.', S, 8),
      st('Akcióterv és terv-újrakalibrálás', 'Intézkedések felelősökkel, a terv módosítása.', S, 8),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'Az értékesítési adatok részletezettsége.',
    client: { days: 2, who: 'értékesítés és pénzügy' },
    external: [],
    assumptions: [],
  },
  'PA-05': {
    goal: 'Költségszerkezet- és árazás-felülvizsgálat; fedezetjavító intézkedések termék- és vevőszinten.',
    steps: [
      st('Fedezetelemzés', 'Termék- és vevőszintű fedezet, költségallokáció.', J, 12),
      st('Költségszerkezet', 'Fix és változó költségek, megtakarítási lehetőségek.', S, 8),
      st('Árazási javaslat', 'Árkorrekció, kedvezménypolitika.', S, 6),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'A költségadatok bontottsága.',
    client: { days: 2, who: 'pénzügy és értékesítés' },
    external: [],
    assumptions: [],
  },
  'PA-06': {
    goal: 'Átlátható adósságszerkezet és refinanszírozási terv a lejárati profilhoz igazítva.',
    steps: [
      st('Adósságszerkezet', 'Hitelek, lejáratok, kamatok, biztosítékok, kovenánsok.', J, 6),
      st('Adósságszolgálati képesség', 'Cash-flow alapú elemzés, stresszforgatókönyv.', S, 8),
      st('Refinanszírozási terv', 'Opciók, időzítés, bankoknak szóló anyag.', S, 6),
      st('Partneri felülvizsgálat', 'Banki egyeztetés támogatása.', P, 3),
    ],
    spread: [0.85, 1.5],
    uncertainty: 'A hitelszerződések száma és a bankok hozzáállása.',
    client: { days: 1, who: 'pénzügyi vezető' },
    external: ['Banki díjak'],
    assumptions: [],
  },
  'PA-07': {
    goal: '13 hetes cash-flow terv és forgótőke-intézkedések (beszedés, készlet, szállítói feltételek).',
    steps: [
      st('Cash-flow modell', 'Heti bontás, forgatókönyvek.', S, 8),
      st('Forgótőke-elemzés', 'Vevők, készletek, szállítók; gyors intézkedések.', J, 8),
      st('Rövid távú finanszírozás', 'Folyószámlahitel, faktoring opciói.', S, 4),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 1),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'A likviditási hiány mértéke.',
    client: { days: 2, who: 'pénzügy' },
    external: ['Finanszírozási díjak'],
    assumptions: [],
  },
  'PA-08': {
    goal: 'Az adófolyószámla egyeztetve, a tartozás rendezve vagy fizetési könnyítés kérve, a köztartozásmentes státusz visszaszerezve.',
    steps: [
      st('Folyószámla-egyeztetés', 'NAV-folyószámla és könyvelés összevetése adónemenként.', J, 6),
      st('Rendezési javaslat', 'Befizetés, átvezetés, részletfizetési kérelem.', S, 4),
      st('Kérelmek és beadványok', 'Fizetési könnyítési kérelem, átvezetések.', S, 3),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'Az eltérések száma és hogy a NAV elfogadja-e a fizetési könnyítést.',
    client: { days: 1, who: 'könyvelő' },
    external: ['A tartozás és a késedelmi pótlék összege'],
    assumptions: [],
  },
  'PA-09': {
    goal: 'Az adóellenőrzési megállapítások okai megszüntetve, adózási folyamatok és kontrollok javítva.',
    steps: [
      st('Megállapítások elemzése', 'Határozatok és önellenőrzések okainak csoportosítása.', S, 6),
      st('Folyamat-felülvizsgálat', 'Adózási folyamatok, felelősök, kontrollpontok.', S, 8),
      st('Kontrollok bevezetése', 'Ellenőrzőlisták, havi egyeztetés.', J, 6),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'A megállapítások száma és típusa.',
    client: { days: 2, who: 'könyvelő és pénzügy' },
    external: [],
    assumptions: [],
  },
  'PA-10': {
    goal: 'A függő kötelezettségek teljes listája, lehívási kockázattal; tranzakciónál kártalanítási kikötés.',
    steps: [
      st('Kötelezettségvállalások kigyűjtése', 'Kezességek, garanciák, biztosítékok szerződésenként.', J, 3, 1),
      st('Lehívási kockázat', 'Valószínűség és összeg tételenként.', S, 2, 1),
      st('Kezelési javaslat', 'Felszabadítás, kártalanítás, vételár-korrekció.', S, 4),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    driver: { label: 'Kötelezettségvállalás', unit: 'db', default: 4 },
    spread: [0.85, 1.4],
    uncertainty: 'A szerződések száma és elérhetősége.',
    client: { days: 1, who: 'pénzügy' },
    external: [],
    assumptions: [],
  },
  'PA-11': {
    goal: 'Ügyvédi értékelés a perek várható kimeneteléről, céltartalék-javaslat, tranzakciós kikötések.',
    steps: [
      st('Periratok áttekintése', 'Peres iratok, beadványok, eljárási állás peres ügyenként.', S, 1, 4),
      st('Kimenetel és összeg értékelése', 'Valószínűség, várható összeg, időtáv ügyenként.', P, 0, 1.5),
      st('Céltartalék-javaslat', 'Számviteli megítélés.', S, 2, 0, 'ACCOUNTING'),
      st('Tranzakciós kikötések', 'Specifikus kártalanítás, perkezelési jogok.', S, 3),
    ],
    driver: { label: 'Folyamatban lévő per', unit: 'db', default: 2 },
    spread: [0.8, 1.6],
    uncertainty: 'A perek száma és bonyolultsága.',
    client: { days: 1, who: 'ügyvezető és a cég jogi képviselője' },
    external: ['A perek képviseletének díja (nem része)'],
    assumptions: [],
  },
  'PA-12': {
    goal: 'A támogatási feltételek teljesítése igazolva; tulajdonosváltásnál a támogató hozzájárulása beszerezve.',
    steps: [
      st('Szerződések áttekintése', 'Fenntartási kötelezettség, tulajdonosváltási korlát, visszafizetési esetek támogatásonként.', S, 1, 3),
      st('Megfelelés dokumentálása', 'Mutatók, beszámolók, igazolások.', J, 0, 3),
      st('Hozzájárulási kérelem', 'Kérelem a támogatóhoz, ha szükséges.', S, 0, 2),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 1),
    ],
    driver: { label: 'Támogatási szerződés', unit: 'db', default: 2 },
    spread: [0.85, 1.5],
    uncertainty: 'A támogatások száma és a támogató eljárási ideje.',
    client: { days: 1, who: 'pályázati felelős' },
    external: [],
    assumptions: [],
  },
  'PA-13': {
    goal: 'Banki hozzájárulás (waiver) vagy refinanszírozás a kovenánssértés vagy a tulajdonosváltási záradék kezelésére.',
    steps: [
      st('Hitelszerződések elemzése', 'Kovenánsok, záradékok, következmények szerződésenként.', S, 2, 2),
      st('Megoldási javaslat', 'Waiver, módosítás vagy refinanszírozás.', S, 6),
      st('Banki kérelem és anyag', 'Indoklás, előrejelzés, intézkedési terv.', S, 4),
      st('Partneri részvétel', 'Banki tárgyalás.', P, 3, 1),
    ],
    driver: { label: 'Érintett hitelszerződés', unit: 'db', default: 1 },
    spread: [0.8, 1.7],
    uncertainty: 'A bank hozzáállása.',
    client: { days: 1, who: 'pénzügyi vezető' },
    external: ['Banki módosítási díj'],
    assumptions: [],
  },
  'PA-14': {
    goal: 'Időben elindított refinanszírozás és a lejáratig tartó likviditási terv.',
    steps: [
      st('Lejárati profil', 'Lejáratok, feltételek.', J, 3),
      st('Likviditási terv', 'A lejáratig havi bontásban.', S, 6),
      st('Refinanszírozási anyag', 'Bankoknak szóló összefoglaló, ajánlatkérés.', S, 4),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 1),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'Hány bankkal kell tárgyalni.',
    client: { days: 1, who: 'pénzügyi vezető' },
    external: ['Banki díjak'],
    assumptions: [],
  },
  'PA-15': {
    goal: 'A tagi kölcsönök dokumentálva és rendezve (visszafizetés vagy tőkésítés) a tranzakció előtt.',
    steps: [
      st('Kölcsönök egyeztetése', 'Egyenlegek, kamatok, szerződések.', J, 2, 1),
      st('Rendezési opciók és adóhatás', 'Visszafizetés, tőkésítés, elengedés adóhatása.', S, 4),
      st('Okiratok', 'Szerződések, határozatok.', S, 0, 1.5, 'LEGAL'),
      st('Partneri jóváhagyás', 'Jóváhagyás.', P, 1),
    ],
    driver: { label: 'Tagi kölcsön', unit: 'db', default: 2 },
    spread: [0.85, 1.4],
    uncertainty: 'A kölcsönök száma és a hiányzó dokumentáció.',
    client: { days: 1, who: 'tulajdonos' },
    external: ['Illeték tőkésítésnél (ha van)'],
    assumptions: [],
  },
  'PA-16': {
    goal: 'Beszámoló-közzétételi határidőnapló, felelős és könyvelői szerződésbe épített határidő.',
    steps: [st('Határidőnapló', 'Beszámoló, közzététel, bevallások.', J, 2), st('Könyvelői szerződés felülvizsgálata', 'Határidők, felelősség.', S, 2)],
    spread: [0.85, 1.3],
    uncertainty: 'Kell-e késedelmes közzétételt pótolni.',
    client: { days: 0.5, who: 'ügyvezető' },
    external: ['Esetleges mulasztási bírság'],
    assumptions: [],
  },
  'PA-17': {
    goal: 'Az osztalékfizetés jogszerűsége megvizsgálva; szükség esetén a visszafizetés rendezve.',
    steps: [
      st('Jogszerűségi vizsgálat', 'Tőkevédelmi szabályok, határozatok, közbenső mérleg.', S, 6),
      st('Számviteli és adóhatás', 'Visszafizetés könyvelése és adózása.', S, 3, 0, 'TAX'),
      st('Határozatok és megállapodások', 'Visszafizetési megállapodás vagy pótlólagos határozat.', J, 3),
      st('Partneri jóváhagyás', 'Jóváhagyás.', P, 1),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'Hány évet és mekkora összeget érint.',
    client: { days: 0.5, who: 'tulajdonosok' },
    external: [],
    assumptions: [],
  },
  'PA-18': {
    goal: 'A vezetői levélben jelzett kontrollhiányosságok intézkedési terve felelősökkel és határidőkkel, a fő pontok lezárva.',
    steps: [
      st('Megállapítások rendezése', 'A vezetői levél pontjainak kockázat szerinti rangsora.', S, 3),
      st('Intézkedési terv', 'Megállapításonként kontroll, felelős, határidő.', J, 2, 1.5),
      st('Kontrollok kialakítása', 'Jóváhagyási rend, egyeztetések, hozzáférések.', S, 0, 1.5),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 1),
    ],
    driver: { label: 'Vezetői levél megállapítása', unit: 'db', default: 5 },
    spread: [0.85, 1.4],
    uncertainty: 'A megállapítások száma és súlya.',
    client: { days: 2, who: 'pénzügy és folyamatgazdák' },
    external: [],
    assumptions: [],
  },
  'PA-19': {
    goal: 'Igényfelmérés alapján megfelelő limitű felelősségbiztosítás.',
    steps: [
      st('Igényfelmérés', 'Tevékenységek, szerződéses elvárások, kitettség.', S, 4),
      st('Ajánlatok összevetése', 'Alkusszal együttműködve, fedezet és kizárások.', J, 4),
      st('Partneri felülvizsgálat', 'Javaslat.', P, 1),
    ],
    spread: [0.85, 1.3],
    uncertainty: 'A tevékenység kockázatossága.',
    client: { days: 0.5, who: 'ügyvezető' },
    external: ['A biztosítás díja'],
    assumptions: [],
  },
  'PA-20': {
    goal: 'A beszámoló és az adattáblák eltérése egyeztetve; az ok megszüntetve.',
    steps: [st('Egyeztetés', 'Tábla és főkönyv összevetése, időszakok, nem könyvelt tételek.', J, 6), st('Eltérések értékelése', 'Korrekciós javaslat.', S, 3)],
    spread: [0.85, 1.5],
    uncertainty: 'Az eltérés oka: adattábla-hiba vagy könyvelési hiba.',
    client: { days: 1, who: 'könyvelő' },
    external: [],
    assumptions: [],
  },
  'EPI-01': {
    goal: 'Kötbérplafon és vis maior-rendelkezés a futó szerződésekben; egységes szerződésminta a jövőre.',
    steps: [
      st('Futó szerződések átvizsgálása', 'Kötbér, plafon, vis maior szerződésenként.', S, 1, 1.5),
      st('Szerződésminta', 'Egységes minta kötbérplafonnal, vis maior és árkorrekciós rendelkezéssel.', S, 8),
      st('Újratárgyalás támogatása', 'Módosítási javaslat és tárgyalás szerződésenként.', P, 0, 2),
    ],
    driver: { label: 'Újratárgyalandó futó szerződés', unit: 'db', default: 4 },
    spread: [0.7, 1.8],
    uncertainty: 'A megrendelők tárgyalási hajlandósága (közbeszerzésnél módosítás korlátozott).',
    client: { days: 2, who: 'ügyvezető, projektvezetők' },
    external: [],
    assumptions: [],
  },
  'EPI-02': {
    goal: 'Csökkenő közszféra-függés: tenderstratégia és magánszektorbeli keretszerződés-célok.',
    steps: [
      st('Megrendelői portfólió-elemzés', 'Fedezet és kockázat megrendelőnként.', S, 6),
      st('Piaci célszegmensek', 'Magánszektorbeli lehetőségek, versenytársak.', J, 10),
      st('Tender- és értékesítési stratégia', 'Célok, erőforrás, mérföldkövek.', S, 10),
      st('Partneri felülvizsgálat', 'Vezetői döntés-előkészítő.', P, 2),
    ],
    spread: [0.85, 1.5],
    uncertainty: 'A piaci elemzés mélysége.',
    client: { days: 2, who: 'ügyvezető, értékesítés' },
    external: [],
    assumptions: ['A végrehajtás (értékesítés, tenderek) az ügyfél feladata'],
  },
  'EPI-03': {
    goal: 'Projektkontrolling és készültségi fok szerinti bevétel-elszámolás, időbeli elhatárolással.',
    steps: [
      st('Projektek felmérése', 'Futó projektek költség- és bevételi adatai.', J, 2, 1.5),
      st('Elszámolási módszer', 'Készültségi fok mérése, számviteli politika kiegészítése.', S, 6),
      st('Korrekciók', 'Elhatárolások projektenként.', S, 0, 1),
      st('Projektkontrolling-sablon', 'Havi riport projektenként.', J, 6),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 1),
    ],
    driver: { label: 'Futó projekt', unit: 'db', default: 6 },
    spread: [0.85, 1.4],
    uncertainty: 'A projektek száma és a költségadatok minősége.',
    client: { days: 2, who: 'pénzügy és projektvezetők' },
    external: [],
    assumptions: [],
  },
  'EPI-04': {
    goal: 'Aktualizált munkavédelmi kockázatértékelés és dokumentált alvállalkozói oktatás.',
    steps: [
      st('Dokumentáció átvizsgálása', 'Kockázatértékelés, oktatási nyilvántartás.', S, 3),
      st('Kockázatértékelés aktualizálása', 'Munkaterületenként.', J, 2, 2),
      st('Alvállalkozói oktatási rend', 'Oktatási anyag és nyilvántartás.', J, 4),
    ],
    driver: { label: 'Munkaterület / telephely', unit: 'db', default: 3 },
    spread: [0.85, 1.4],
    uncertainty: 'A munkaterületek száma.',
    client: { days: 1, who: 'munkavédelmi felelős' },
    external: ['Munkavédelmi szakember díja, ha a cégnek nincs'],
    assumptions: [],
  },
  'ITF-01': {
    goal: 'Licenctiszta termék: az érintett copyleft komponensek cserélve vagy megfelelően licencelve, nyílt forráskódú szabályzattal.',
    steps: [
      st('Licencszkennelés', 'Függőségek és licencek listája, kockázati besorolás.', J, 6),
      st('Jogi értékelés komponensenként', 'Az üzleti modellre gyakorolt hatás.', S, 0, 1.5),
      st('Csere vagy licencelési javaslat', 'Alternatívák, kereskedelmi licenc.', S, 0, 1, 'ADVISORY'),
      st('Nyílt forráskódú szabályzat', 'Engedélyezett licencek, jóváhagyási rend.', S, 5),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    driver: { label: 'Érintett komponens', unit: 'db', default: 6 },
    spread: [0.8, 1.6],
    uncertainty: 'Az érintett komponensek száma; a cserét a fejlesztők végzik (nem része).',
    client: { days: 3, who: 'fejlesztési vezető' },
    external: ['Licencszkennelő eszköz díja', 'Kereskedelmi licencdíjak'],
    assumptions: [],
  },
  'ITF-02': {
    goal: 'Felelősségkorlátozás és SLA-kötbérplafon az ügyfélszerződésekben; egységes szerződésminta.',
    steps: [
      st('Szerződések átvizsgálása', 'Felelősség, kötbér, SLA szerződésenként.', S, 1, 1.5),
      st('Szerződésminta', 'Felelősségkorlátozás, kötbérplafon, kizárások.', S, 8),
      st('Újratárgyalás támogatása', 'Módosítási javaslat és tárgyalás szerződésenként.', P, 0, 1.5),
    ],
    driver: { label: 'Újratárgyalandó ügyfélszerződés', unit: 'db', default: 4 },
    spread: [0.7, 1.8],
    uncertainty: 'Az ügyfelek tárgyalási hajlandósága.',
    client: { days: 1, who: 'ügyvezető, ügyfélkapcsolat' },
    external: [],
    assumptions: [],
  },
  'ITF-03': {
    goal: 'ISMS-alapok és NIS2-felmérés; sérülékenységvizsgálat és javítási terv.',
    steps: [
      st('NIS2-érintettség és rés-elemzés', 'Kötelezettségek, jelenlegi állapot.', S, 10),
      st('ISMS-alapdokumentumok', 'Informatikai biztonsági szabályzat, kockázatelemzés, incidenskezelés.', J, 16),
      st('Sérülékenységvizsgálat koordinálása', 'Külső szolgáltató kiválasztása, eredmények értékelése.', S, 6),
      st('Javítási terv', 'Prioritások, felelősök.', S, 6),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    spread: [0.85, 1.5],
    uncertainty: 'A rendszerek száma és a sérülékenységvizsgálat eredménye.',
    client: { days: 3, who: 'IT-vezető' },
    external: ['Sérülékenységvizsgálat (penetrációs teszt) díja', 'Tanúsítás díja (ha kell)'],
    assumptions: [],
  },
  'ITF-04': {
    goal: 'Architektúra-dokumentáció és forráskód-letéti megállapodás a kulcsügyfelekkel.',
    steps: [
      st('Dokumentációs hiánylista', 'Mi van meg, mi kell az ügyfeleknek.', S, 4),
      st('Dokumentációs sablon és felülvizsgálat', 'Sablon a fejlesztőknek, elkészült anyagok ellenőrzése.', J, 8),
      st('Forráskód-letéti megállapodás', 'Letéti szerződés ügyfelenként.', S, 2, 2, 'LEGAL'),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 1),
    ],
    driver: { label: 'Letétet kérő kulcsügyfél', unit: 'db', default: 2 },
    spread: [0.85, 1.4],
    uncertainty: 'A dokumentációt a fejlesztők írják (nem része); a letétkezelő kiválasztása.',
    client: { days: 4, who: 'fejlesztők' },
    external: ['Letétkezelő díja'],
    assumptions: [],
  },
  'KON-01': {
    goal: 'Megfelelő szakmai felelősségbiztosítási fedezet és felelősségkorlátozás az ügyfélszerződésekben.',
    steps: [
      st('Kitettség és fedezet összevetése', 'Szerződések, ügyfélkör, károk.', S, 3),
      st('Szerződésminta-kiegészítés', 'Felelősségkorlátozó rendelkezés.', S, 3),
      st('Ajánlatok összevetése', 'Alkusszal együtt.', J, 2),
    ],
    spread: [0.85, 1.3],
    uncertainty: 'Kell-e a meglévő ügyfélszerződéseket is módosítani.',
    client: { days: 0.5, who: 'ügyvezető' },
    external: ['A biztosítás díja'],
    assumptions: [],
  },
  'KON-02': {
    goal: 'Aktualizált pénzmosás elleni szabályzat, pótolt ügyfél-átvilágítások, munkatársi képzés.',
    steps: [
      st('Szabályzat aktualizálása', 'A hatályos jogszabály és a felügyelet mintája szerint.', S, 6),
      st('Ügyfél-átvilágítások pótlása', 'Adatlapok, kockázati besorolás ügyfelenként.', J, 0, 0.75),
      st('Ellenőrzés', 'Mintavételes felülvizsgálat.', S, 3),
      st('Képzés', 'Munkatársi oktatás, jelenléti ív, teszt.', S, 3),
    ],
    driver: { label: 'Pótlandó ügyfél-átvilágítás', unit: 'ügyfél', default: 40 },
    spread: [0.85, 1.4],
    uncertainty: 'A hiányos ügyfél-átvilágítások száma.',
    client: { days: 3, who: 'ügyfélkapcsolattartók: ügyféladatok bekérése' },
    external: [],
    assumptions: [],
  },
  'KON-03': {
    goal: 'Indexálási záradék és felülvizsgált díjszabás, ügyfélkommunikációs tervvel.',
    steps: [
      st('Díjelemzés', 'Ügyfelenkénti díj és ráfordítás, alulárazott szerződések.', J, 8),
      st('Díjszabás és indexálási záradék', 'Új díjstruktúra, szerződéses szöveg.', S, 6),
      st('Ügyfélkommunikációs terv', 'Levél- és tárgyalási forgatókönyv.', S, 4),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'Az ügyfélkör mérete és az időrögzítési adatok minősége.',
    client: { days: 2, who: 'ügyvezető' },
    external: [],
    assumptions: [],
  },
  'KON-04': {
    goal: 'Tulajdonosi megállapodás, üzletrész-átadási és vezetési terv az utódláshoz.',
    steps: [
      st('Tulajdonosi célok', 'Interjúk, utódlási forgatókönyvek.', S, 6),
      st('Megállapodás és átadási terv', 'Elővásárlás, értékelés, ütemezés.', S, 12),
      st('Adózási hatás', 'Átadási formák adó- és illetékhatása.', S, 4, 0, 'TAX'),
      st('Partneri irányítás', 'Egyeztetések.', P, 4),
    ],
    spread: [0.8, 1.7],
    uncertainty: 'A tulajdonosok és a lehetséges utódok egyetértése.',
    client: { days: 2, who: 'tulajdonosok' },
    external: ['Közjegyzői díj'],
    assumptions: [],
  },
  'GYA-01': {
    goal: 'Hiánytalan telephelyi és környezetvédelmi engedélyek, megújítási naptárral.',
    steps: [
      st('Engedély-felülvizsgálat', 'Tevékenységenként szükséges és meglévő engedélyek.', S, 2, 1),
      st('Hiánypótlási terv', 'Eljárások, határidők, szakhatóságok.', J, 2, 1),
      st('Nyilvántartás és naptár', 'Felelős, emlékeztetők.', J, 2),
    ],
    driver: { label: 'Engedély', unit: 'db', default: 6 },
    spread: [0.85, 1.5],
    uncertainty: 'A hiányzó engedélyek száma; az eljárások lefolytatása külön megbízás.',
    client: { days: 1, who: 'telephelyvezető' },
    external: ['Hatósági díjak, környezetvédelmi szakértő'],
    assumptions: [],
  },
  'GYA-02': {
    goal: 'Eszközállapot-felmérés, beruházási és karbantartási terv a halasztott karbantartás felszámolására.',
    steps: [
      st('Eszközállapot-felmérés', 'Kritikus gépek, életkor, meghibásodási adatok.', J, 10),
      st('Beruházási és karbantartási terv', 'Prioritás, költség, ütemezés.', S, 10),
      st('Finanszírozási hatás', 'Cash-flow és finanszírozási lehetőségek.', S, 4),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    spread: [0.85, 1.5],
    uncertainty: 'A géppark mérete; műszaki állapotfelmérés külső szakértővel külön díjas.',
    client: { days: 3, who: 'műszaki vezető' },
    external: ['Műszaki szakértő díja'],
    assumptions: [],
  },
  'GYA-03': {
    goal: 'A minőségügyi eltérések lezárva, a tanúsítás megújítva, felelős kijelölve.',
    steps: [
      st('Eltérések elemzése', 'Audit-megállapítások és vevői elvárások.', S, 4),
      st('Intézkedési terv és dokumentáció', 'Eljárások, nyilvántartások frissítése.', J, 10),
      st('Belső audit', 'Felkészülés a tanúsító auditra.', S, 6),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'Az eltérések száma.',
    client: { days: 3, who: 'minőségügyi felelős' },
    external: ['A tanúsító szervezet díja'],
    assumptions: [],
  },
  'GYA-04': {
    goal: 'Árkorrekciós záradékok a vevői szerződésekben és beszerzési fedezeti stratégia.',
    steps: [
      st('Kitettség-elemzés', 'Alapanyag- és energiaár-érzékenység, fix áras szerződések.', S, 6),
      st('Árkorrekciós záradék', 'Minta és szerződésenkénti módosítási javaslat.', S, 2, 1, 'LEGAL'),
      st('Fedezeti stratégia', 'Beszerzési szerződések, határidős ügyletek.', S, 6),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    driver: { label: 'Fix áras vevői szerződés', unit: 'db', default: 4 },
    spread: [0.8, 1.6],
    uncertainty: 'A vevők elfogadják-e az árkorrekciót.',
    client: { days: 2, who: 'beszerzés és értékesítés' },
    external: ['Fedezeti ügyletek költsége'],
    assumptions: [],
  },
  'TAN-01': {
    goal: 'Felelősségkorlátozó ügyfélszerződés-minta és megfelelő biztosítási limit.',
    steps: [
      st('Szerződések és fedezet áttekintése', 'Felelősségi rendelkezések, biztosítás.', S, 4),
      st('Szerződésminta', 'Felelősségkorlátozás, kizárások.', S, 5),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 1),
    ],
    spread: [0.85, 1.3],
    uncertainty: 'Kell-e a futó szerződéseket módosítani.',
    client: { days: 0.5, who: 'ügyvezető' },
    external: ['Biztosítási díj'],
    assumptions: [],
  },
  'TAN-02': {
    goal: 'Ügyfél- és tudásmegosztás a partnerek között, ügyfélcsábítási és versenytilalmi megállapodásokkal.',
    steps: [
      st('Ügyfél- és tudástérkép', 'Mely ügyfél és tudás kötődik egy-egy partnerhez.', S, 6),
      st('Megállapodások', 'Ügyfélcsábítási tilalom és versenytilalom partnerenként.', S, 0, 3, 'LEGAL'),
      st('Tudásmegosztási terv', 'Párosítás, dokumentálás, ügyfélátadás.', S, 6),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    driver: { label: 'Érintett partner', unit: 'fő', default: 3 },
    spread: [0.8, 1.6],
    uncertainty: 'A partnerek egyetértése.',
    client: { days: 2, who: 'partnerek' },
    external: [],
    assumptions: [],
  },
  'TAN-03': {
    goal: 'Projektszintű időrögzítés, fedezetszámítás és árazási irányelv.',
    steps: [
      st('Kihasználtság és fedezet elemzése', 'Projekt- és ügyfélszinten.', J, 10),
      st('Időrögzítési rend', 'Kategóriák, kötelező rögzítés, riport.', S, 4),
      st('Árazási irányelv', 'Díjszámítás, kedvezmények, minimum fedezet.', S, 6),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 2),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'A meglévő időadatok minősége.',
    client: { days: 2, who: 'vezetés' },
    external: ['Időrögzítő szoftver díja'],
    assumptions: [],
  },
  'TAN-04': {
    goal: 'A módszertanok és szellemi termékek vagyoni jogai szerződésben a cégnél.',
    steps: [
      st('Érintettek és alkotások', 'Munkatársak, megbízottak, alkotások.', J, 3),
      st('Szerződés-kiegészítések', 'Vagyoni jogi rendelkezés személyenként.', J, 0, 1),
      st('Felülvizsgálat', 'Minta és egyedi esetek.', S, 3, 0.25),
    ],
    driver: { label: 'Érintett munkatárs / megbízott', unit: 'fő', default: 8 },
    spread: [0.85, 1.4],
    uncertainty: 'Az érintettek száma és együttműködése.',
    client: { days: 1, who: 'HR' },
    external: [],
    assumptions: [],
  },
  'KER-01': {
    goal: 'Korosított készlet, elszámolt értékvesztés és kiárusítási terv.',
    steps: [
      st('Készletkorosítás', 'Forgási sebesség cikkenként.', J, 8),
      st('Értékvesztés', 'Számítás és könyvelési javaslat.', S, 4),
      st('Kiárusítási terv', 'Akciók, csatornák, várható bevétel.', S, 4, 0, 'ADVISORY'),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 1),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'A cikkszám és a készletnyilvántartás minősége.',
    client: { days: 2, who: 'raktár és pénzügy' },
    external: [],
    assumptions: [],
  },
  'KER-02': {
    goal: 'Újratárgyalt forgalmazói szerződés és diverzifikált termékportfólió.',
    steps: [
      st('Szerződés-elemzés', 'Felmondás, kizárólagosság, megújítás.', S, 4),
      st('Tárgyalási stratégia és javaslat', 'Módosítási javaslat.', S, 6),
      st('Tárgyalás támogatása', 'Részvétel a tárgyaláson.', P, 4),
      st('Portfólió-diverzifikáció', 'Alternatív termékek és szállítók.', S, 6, 0, 'ADVISORY'),
    ],
    spread: [0.75, 1.8],
    uncertainty: 'A gyártó hozzáállása.',
    client: { days: 2, who: 'ügyvezető' },
    external: [],
    assumptions: [],
  },
  'KER-03': {
    goal: 'Hitelkeret-szabályzat és hitelbiztosítás vagy faktoring a vevői kockázatra.',
    steps: [
      st('Vevői kockázat elemzése', 'Fizetési fegyelem, koncentráció.', J, 6),
      st('Hitelkeret-szabályzat', 'Vevőminősítés, keretek, jóváhagyás.', S, 6),
      st('Hitelbiztosítás / faktoring ajánlatok', 'Összevetés.', S, 3),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'A vevőkör mérete.',
    client: { days: 1, who: 'pénzügy és értékesítés' },
    external: ['Hitelbiztosítási vagy faktoring díj'],
    assumptions: [],
  },
  'KER-04': {
    goal: 'Devizakitettség-kimutatás, fedezeti politika és árazási mechanizmus.',
    steps: [
      st('Kitettség-kimutatás', 'Devizanemenként beszerzés és értékesítés.', J, 6),
      st('Fedezeti politika', 'Eszközök, limitek, felelős.', S, 6),
      st('Árazási mechanizmus', 'Árfolyamküszöb az eladási árakban.', S, 4),
      st('Partneri felülvizsgálat', 'Jóváhagyás.', P, 1),
    ],
    spread: [0.85, 1.4],
    uncertainty: 'A devizanemek és ügyletek száma.',
    client: { days: 1, who: 'pénzügy' },
    external: ['Banki fedezeti ügyletek költsége'],
    assumptions: [],
  },
};

/**
 * Általános terv üzletágonként – egyedi (katalóguson kívüli) tételhez. Széles
 * sávval, mert a tényleges munka a tétel ismerete nélkül csak nagyságrend.
 */
export function genericTemplate(division: Division): PlanTemplate {
  return {
    goal: 'A javítás terjedelme egyedileg pontosítandó: ez általános sablon, a tételre szabott terv még nincs.',
    steps: [
      st('Helyzetfeltárás', 'Iratok, interjúk, a hiányosság pontos körülhatárolása.', S, 6),
      st('Megoldási javaslat', 'Opciók, ajánlott megoldás, intézkedési terv.', S, 8),
      st('Kidolgozás', 'A szükséges dokumentumok, számítások elkészítése.', J, 10),
      st('Partneri felülvizsgálat', 'Jóváhagyás, egyeztetés az ügyféllel.', P, 2),
    ],
    spread: [0.6, 2],
    uncertainty: `Általános ${division === 'LEGAL' ? 'jogi' : division === 'TAX' ? 'adó' : division === 'ACCOUNTING' ? 'számviteli' : division === 'HR' ? 'HR' : 'tanácsadói'} sablon: a sáv széles, a tételre szabott lépésekkel pontosítsd.`,
    client: { days: 1, who: 'érintett vezető' },
    external: [],
    assumptions: ['Nagyságrendi becslés'],
  };
}
